### ISSUE TITLE
为每个滚动元素添加点击事件，拷贝的元素无效

### ISSUE THREAD

**Issue by ajaxQWER** [chenxuan0000/vue-seamless-scroll#10]
需求：当滚动元素为图片是，实现点击滚动小图展示大图。
实现：在img标签上添加@click方法
问题：原滚动列表有事件，拷贝的列表无事件，何解？

**Comment by ajaxQWER** [comment]
用一个粗鄙的方法实现这个功能：

![4q 92 0785 6l8msc0uz a6](https://user-images.githubusercontent.com/16046545/39006297-38360e7a-4435-11e8-8a92-797a5fbdb64b.png)
希望大佬能在插件里面解决一下这个问题？

**Comment by chenxuan0000** [comment]
@ajaxQWER  是这样的我这里面只对元素进行了dom层的复制，没有类似jq的clone(true)一样的连带节点事件的复制。之前有人提过这个问题我简单的加个参数处理下吧，后期加好@你深拷贝的代价太大了。

**Comment by ajaxQWER** [comment]
@chenxuan0000 看了你源码的实现，我也想不到有什么办法把绑定的事件拷贝到复制的元素上，就搞了这个粗鄙的方法暂时解决了这个问题，还有一点就是mounted的时候找不到dom，是因为组件是根据数据异步的加载出来的？

**Comment by chenxuan0000** [comment]
@ajaxQWER  哈哈 目前来看没有什么特别好的方法，给你个相对优雅的解决方案 ，用事件代理可以相对好点，不过没有点击的这个需求，自己后绑定也是可以的没毛病。

**Comment by ajaxQWER** [comment]
@chenxuan0000 跟我的实现方式差不多

**Comment by chenxuan0000** [comment]
@ajaxQWER  https://zhuanlan.zhihu.com/p/26536815
参考这个给外层绑定事件，这样不用setTimeout了。
