### ISSUE TITLE
单步，上下滚动时，后面动态添加的数据不滚动，被直接跳过。回到第一条

### ISSUE THREAD

**Issue by chenxia-123** [chenxuan0000/vue-seamless-scroll#100]
比如，我有一个数组，里面有5条数据，之后过了10秒，往数组中新增3条数据。那么这3条数据在单步滚动的时候是会被跳过。到了第五条后直接就回到第一条

**Comment by chenxuan0000** [comment]
再本地测试可以，
@chenxia-123 
Version（版本号）

Steps to reproduce（复现步骤）

What is expected? （期望效果）

What is actually happening? （目前现状描述）

完成后重新打开issue
