### ISSUE TITLE
动态渲染的内容无法在复制的元素中正常显示

### ISSUE THREAD

**Issue by lllyyylll2** [chenxuan0000/vue-seamless-scroll#104]
实际应用场景为，滚动内容包含二维码，该二维码是通过vue-qr异步渲染的，导致滚动组件的复制元素innerHtml尚未包含二维码的链接。

求解决办法或解决思路。

**Comment by chenxuan0000** [comment]
@lllyyylll2 
这种场景比较少，判断倒异步图片加载完成后，手动依次调用组件内部的方法cancle()、_initMove()，强制重新渲染。

**Comment by chenchen0501** [comment]
我也遇到了这种情况，图片是动态渲染的，在复制层无法显示，要过一段时间才能显示（el-image），但是用原声img没有问题
