### ISSUE TITLE
:data='Array' 中的数组有什么要求吗

### ISSUE THREAD

**Issue by adouwt** [chenxuan0000/vue-seamless-scroll#11]
我现在使用后的问题：两个相同结构的组件，不同的Array,但是一个滚动一个不滚动，然后将不滚动的那个组件的 ：data='Array'中的Array替换成了可以滚动的Array ，然后这个组件就开始滚动了。这个：data="Array"中的Array 的数组有一定的要求，还是一个页面不能使用多个这样的滚动组件

**Comment by chenxuan0000** [comment]
@adouwt 没要求  limitMoveNum这个字段控制最小滚动的数据量默认是5可能是你数据量小了

**Comment by adouwt** [comment]
我加大数组的长度，果然可以滚动了，不过这个我认为限制为1好点，实际情况数组的长度是不确定吧
