### ISSUE TITLE
建议在使用网站上写上配置项 我直接用没发现配置项 项目运行时数据量不超过5条不滚动 最后翻源码才找到配置 对新手不友好

### ISSUE THREAD

**Issue by c1184405532** [chenxuan0000/vue-seamless-scroll#110]
你的项目中文网： https://chenxuan1993.gitee.io/component-document/index_prod#/component/seamless-others
建议在这边写上所有的配置项

**Comment by chenxuan0000** [comment]
> 你的项目中文网： https://chenxuan1993.gitee.io/component-document/index_prod#/component/seamless-others
> 建议在这边写上所有的配置项

@c1184405532 
https://github.com/chenxuan0000/vue-seamless-scroll/blob/master/document/README.md#%E9%85%8D%E7%BD%AE%E9%A1%B9
