### ISSUE TITLE
请问`step`如何设置，官方文档上看不到代码

### ISSUE THREAD

**Issue by zhoufanglu** [chenxuan0000/vue-seamless-scroll#112]
如题
![image](https://user-images.githubusercontent.com/24451091/79303256-08697a00-7f21-11ea-92bd-cb049a704d98.png)

```html
<scroll :data="dataList_1"
             class="seamless-warp"
             step="0.5"
>
```
现在这样设置了没有效果，希望大佬能帮忙解决。谢谢

**Comment by chenxuan0000** [comment]
@zhoufanglu 
computed: {
              classOption: function () {
                return {
                  step: 0.5,
                  limitMoveNum: 5
                }
              }
            }

**Comment by zhoufanglu** [comment]
> @zhoufanglu
> https://github.com/chenxuan0000/vue-seamless-scroll/blob/master/examples-src/components/router-one.vue
> 
> ```js
> computed: {
>         classOption () {
>               return {
>                   step: 0.5,
>                   limitMoveNum: 5
>                 }
>             }
>    }
> ```

可以了 谢谢
