### ISSUE TITLE
v-show 相关

### ISSUE THREAD

**Issue by DreamMoeQ** [chenxuan0000/vue-seamless-scroll#114]
设置两个无缝滚动，加上v-show判断是否隐藏显示，通过按钮点击后，原先隐藏的显示出来后不滚动

**Comment by chenxuan0000** [comment]
@chenxuan0000 v-show:false的vue-seamless-srcoll组件内部高度高度为0，计算滚动高度为0；
解决方案：
1、v-show切换后，手动调用this.$refs.xxx._cancle()  this.$refs.xxx._initMove()。
2、v-show为false的autoPlay设为false，切换为false后手动切换为true。
