### ISSUE TITLE
在数据动态splice时数据无法重新渲染(这个问题和limitMoveNum设置紧密相关)

### ISSUE THREAD

**Issue by zhangchangwei** [chenxuan0000/vue-seamless-scroll#115]
当limitMoveNum设置为2(2行数据)时，父组件数据进行动态减少（splice），在子组件（vue-seamless-scroll）上数据依旧显示所删除的那一行数据，只有先将其置空，在循环插入才可以解决，这是为什么呢？

**Comment by chenxuan0000** [comment]
@zhangchangwei 
注意：在变更 (不是替换) 对象或数组时，旧值将与新值相同，因为它们的引用指向同一个对象/数组。Vue 不会保留变更之前值的副本。
https://cn.vuejs.org/v2/api/#vm-watch

我源码里面判断了newVal和oldVal是否一致，直接通过splice虽然可以改变原数组，但是因为newVal和oldVal一致无法触发我内部的更新逻辑，可以这样
```javascript
let copy = [...this.listData]
copy.splice(0,1)
this.listData = copy
```
