### ISSUE TITLE
ul2里面的 click 事件丢失了

### ISSUE THREAD

**Issue by gongdongtao** [chenxuan0000/vue-seamless-scroll#118]
当需要对每个li添加点击事件时，发现ul2中的点击事件丢失了，点击无效

**Comment by lcy813306986** [comment]
这个怎么处理呢？

**Comment by gongdongtao** [comment]
> 这个怎么处理呢？

目前我是通过给li下的每个元素都定义:data-record去解决的

**Comment by gongdongtao** [comment]
> 这个怎么处理呢？

目前我是通过给li下的每个元素都定义:data-record，然后通过事件委托解决的

**Comment by chenxuan0000** [comment]
https://github.com/chenxuan0000/vue-seamless-scroll/blob/master/issuses/problem1.md
