### ISSUE TITLE
当滚动的列表内容，不是一个占据一个块的位置的时候，出现循环滚动漏失列表问题

### ISSUE THREAD

**Issue by adouwt** [chenxuan0000/vue-seamless-scroll#12]
滚动的内容是一个占据一个块的时候，滚动是没有问题的，循环的时候，从1-10 1-10 1-10 ...；如果假设是两个列表占据一行时候，就会出现 1-10 1-8 1-10 这样的问题。应该是先求每个列表的高度，然后乘以总的个数，就是整个滚动的高度，但是当两个内容是在同一行的时候，就会出问题吧。还没看源码，如果说错了，请大神见谅哈!

**Comment by chenxuan0000** [comment]
@adouwt  什么叫两个在同一行 能给个在线的bug demo吗 ？ 
https://jsfiddle.net/ 
在这里用原始的script方式复现下是否可以， 描述的不是很明白意思？

**Comment by adouwt** [comment]
抱歉，经测试，是我的重复性数据导致我判断错误，我关闭这个issue
