### ISSUE TITLE
feat: 数据滚动一遍完成后，能否停止，不再滚动

### ISSUE THREAD

**Issue by QETHAN** [chenxuan0000/vue-seamless-scroll#120]
能不能添加一个配置，当当前数据都滚动过后，就停止滚动。有新数据添加过后，继续滚动

**Comment by jiuru** [comment]
源码中有这个this.$emit('ScrollEnd')

**Comment by chenxuan0000** [comment]
监听到ScrollEnd事件后，autoPlay置为false，新数据如果长度变更会自动开始滚动。
如果只是数组子项属性更新，参考 https://chenxuan0000.github.io/vue-seamless-scroll/zh/guide/10-array-property-update.html
