### ISSUE TITLE
如果页面上有dom操作比如v-if就会出现卡顿

### ISSUE THREAD

**Issue by Mrwangfan** [chenxuan0000/vue-seamless-scroll#123]
![image](https://user-images.githubusercontent.com/22339042/83216386-b496b580-a19b-11ea-880b-132e30c95a20.png)
右边是无缝滚动，左边是列表上的下拉选择，下拉内容是v-if显示，鼠标移入下拉，无缝滚动就会卡顿

**Comment by chenxuan0000** [comment]
@Mrwangfan 频繁操作的建议用v-show
