### ISSUE TITLE
关于请求数据延迟不滚动的问题

### ISSUE THREAD

**Issue by zboboan** [chenxuan0000/vue-seamless-scroll#127]
因为从后台请求数据，页面渲染有延迟，不能滚动，希望有一个 refresh 的方法，能重新计算高度
如果动态添加数据的话，好像也不会重新计算高度  这时希望有一个方法 能重新计算高度

在手机端上，可以拖动list

**Comment by linpeng1** [comment]
复议

**Comment by linbolun** [comment]
+1

**Comment by chenxuan0000** [comment]
https://chenxuan0000.github.io/vue-seamless-scroll/zh/guide/10-array-property-update.html
