### ISSUE TITLE
列表动态追加数据滚动异常

### ISSUE THREAD

**Issue by dengxiaoning** [chenxuan0000/vue-seamless-scroll#128]
在后台接口返回数据后使用 push() 将数据添加到 list 中，会一直向上滚动...... 
![image](https://user-images.githubusercontent.com/26786620/87011096-0e0ded80-c1fa-11ea-908d-f6891d157508.png)

**Comment by chenxuan0000** [comment]
Version（版本号）

Steps to reproduce（复现步骤）

What is expected? （期望效果）

What is actually happening? （目前现状描述）

完成后重新打开issue
