### ISSUE TITLE
IE11下测试，不兼容，无法显示滚动列表数据。

### ISSUE THREAD

**Issue by baizhijian** [chenxuan0000/vue-seamless-scroll#13]
IE11下测试，不兼容，无法显示滚动列表数据。
比如打开演示网址：http://chenxuan1993.gitee.io/component-document/index_prod#/component/seamless-default 就无法正确显示，干脆打不开。

**Comment by chenxuan0000** [comment]
@baizhijian  这个demo页面没有兼容ie babel  这个组件是兼容的

**Comment by chenxuan0000** [comment]
https://chenxuan0000.github.io/vue-seamless-scroll/index.html 这个demo页面做了babel-polyfill
