### ISSUE TITLE
在5k/4k分辨率的大屏上展示，纵向滚动数据会抖动，请问怎么解决？

### ISSUE THREAD

**Issue by 123forget** [chenxuan0000/vue-seamless-scroll#132]
![test](https://user-images.githubusercontent.com/51594928/90973531-79ffa780-e555-11ea-8636-0f185b3f87ff.gif)
前端新手，求解，急！！。

**Comment by chenxuan0000** [comment]
https://chenxuan0000.github.io/vue-seamless-scroll/zh/guide/11-array-length-update.html

**Comment by 2805439601** [comment]
你可以用 vue-seamless-scroll  这个插件
