### ISSUE TITLE
模板中如果绑定了事件，插件复制出来的那一份不会触发该事件

### ISSUE THREAD

**Issue by jQChou** [chenxuan0000/vue-seamless-scroll#133]
![image](https://user-images.githubusercontent.com/19767705/91921827-0ac94680-ecff-11ea-8977-2c398226f383.png)

**Comment by binmomo** [comment]
就是，不知道怎么解决

**Comment by chenxuan0000** [comment]
https://github.com/chenxuan0000/vue-seamless-scroll/blob/master/issuses/problem1.md
@binmomo @jQChou
