### ISSUE TITLE
可否提供一个暂停滚动的方法

### ISSUE THREAD

**Issue by firstblood93** [chenxuan0000/vue-seamless-scroll#134]
现在只能依靠鼠标移入去触发,想用外部按钮去暂停/开启 滚动
看了源码 用了 this.$refs.xx.enter() 模拟这个动作 但是无效

**Comment by jiuru** [comment]
源码中enter()方法的执行，是有条件的，hoverStop必须是true；
暂停可使用_cancle()
再次启动可使用_startMove()

**Comment by firstblood93** [comment]
好的 我试试
