### ISSUE TITLE
获取新数据后如何从头开始滚动

### ISSUE THREAD

**Issue by Corgis** [chenxuan0000/vue-seamless-scroll#136]
获取到新数据后 组件如何从头开始滚动  例如：有没有提供内置方法 动态设置滚动位置的高度

**Comment by littlesunnn** [comment]
给组件一个key,更新数据后让key++

**Comment by chenxuan0000** [comment]
@Corgis @littlesunnn 
https://chenxuan0000.github.io/vue-seamless-scroll/zh/guide/10-array-property-update.html

**Comment by zxjzx** [comment]
咋处理的啊
