### ISSUE TITLE
计算属性更新不及时

### ISSUE THREAD

**Issue by caowei110** [chenxuan0000/vue-seamless-scroll#138]
/*if (!arrayEqual(newData, oldData)) {
          this._cancle()
          this._initMove()
        }*/
 此处复杂结构数组无法判断出不同，导致copyHtml更新不及时。

**Comment by richadlee** [comment]
> /_if (!arrayEqual(newData, oldData)) { this._cancle() this._initMove() }_/
> 此处复杂结构数组无法判断出不同，导致copyHtml更新不及时。

我也遇到这个问题
我使用的是VUE  解决方法是
在vue-seamless-scroll 加入key属性 判断数组长度更新key 然后重新渲染这个组件

**Comment by chenxuan0000** [comment]
@richadlee @richadlee 
https://chenxuan0000.github.io/vue-seamless-scroll/zh/guide/10-array-property-update.html
