### ISSUE TITLE
关于复制图表问题

### ISSUE THREAD

**Issue by qqfei1858** [chenxuan0000/vue-seamless-scroll#139]
有这样的一个需求,需要使用到echrts图表,那么使用无缝滚动组件的时候,无法复制echarts的dom,如图:
![image](https://user-images.githubusercontent.com/26538473/96451108-aed46600-1249-11eb-930c-e3e442b02fc5.png)
![image](https://user-images.githubusercontent.com/26538473/96451390-12f72a00-124a-11eb-83a8-9959944d91ca.png)
请问大佬可有解决方案呢?

**Comment by fanlogfei** [comment]
遇到同样的问题。

**Comment by chenxuan0000** [comment]
@qqfei1858 @fanlogfei 
https://chenxuan0000.github.io/vue-seamless-scroll/zh/guide/09-echart.html
