### ISSUE TITLE
只有一条数据时，有时出现滚动，数据消失。再次更新数据，又不滚动了。这个怎么优化？

### ISSUE THREAD

**Issue by ZhaoYLong** [chenxuan0000/vue-seamless-scroll#142]
只有一条数据时，有时出现滚动，数据消失。再次更新数据，又不滚动了。这个怎么优化？

**Comment by chenxuan0000** [comment]
Version（版本号）

Steps to reproduce（复现步骤）

What is expected? （期望效果）

What is actually happening? （目前现状描述）

完成后重新打开issue
