### ISSUE TITLE
一个页面上有两个滚动的位置，第一个滚动，第二个不滚动如何解决呢？

### ISSUE THREAD

**Issue by hwtdnet** [chenxuan0000/vue-seamless-scroll#145]
一个页面上有两个滚动的位置
第一个滚动
第二个不滚动如何解决呢？

**Comment by chenxuan0000** [comment]
Version（版本号）

Steps to reproduce（复现步骤）

What is expected? （期望效果）

What is actually happening? （目前现状描述）

完成后重新打开issue
