### ISSUE TITLE
大佬，请问不支持点击行的事件吗？

### ISSUE THREAD

**Issue by AwakenedSomeone** [chenxuan0000/vue-seamless-scroll#146]
我自己给每一行添加了事件，但是滚动实现的时候我看到是有两个列表在循环的，所以第二个列表就没有绑定到事件，导致点击行的时候只有第一个列表有事件

**Comment by chenxuan0000** [comment]
@AwakenedSomeone 
https://github.com/chenxuan0000/vue-seamless-scroll/blob/master/issuses/problem1.md
