### ISSUE TITLE
注意事项里left-switch能否给个正常运行demo。

### ISSUE THREAD

**Issue by TomLongJoy** [chenxuan0000/vue-seamless-scroll#149]
![下载](https://user-images.githubusercontent.com/18641052/101333301-6d5b5100-38b1-11eb-8b73-3710df3f8437.jpeg)
![企业微信截图_f27abb08-e223-4cc5-b623-5989d5b7d364](https://user-images.githubusercontent.com/18641052/101333332-751af580-38b1-11eb-9d8e-614f480094e4.png)

**Comment by chenxuan0000** [comment]
https://chenxuan0000.github.io/vue-seamless-scroll/zh/guide/08-switch.html
