### ISSUE TITLE
我这里会出现两排，

### ISSUE THREAD

**Issue by zs310071113** [chenxuan0000/vue-seamless-scroll#156]
我横向的时候会出现两排，也就是第二个float：left不生效，我不知道为啥

**Comment by chenxuan0000** [comment]
@zs310071113 
2.左右的无缝滚动需要给主内容区域（即默认slot插槽提供）设定合适的css width属性(否则无法正确计算实际宽度)。 也可以通过给他设置为display:flex;无需设置css width属性

https://chenxuan0000.github.io/vue-seamless-scroll/zh/guide/08-switch.html
