### ISSUE TITLE
能获取滚动元素的值么？

### ISSUE THREAD

**Issue by wubodanran** [chenxuan0000/vue-seamless-scroll#16]
![image](https://user-images.githubusercontent.com/29586966/40817901-2875ffe0-6587-11e8-8c4e-2905cfac5d53.png)
比如：这个能获取到上一个即将消失的li，和他后面的li

**Comment by chenxuan0000** [comment]
@wubodanran  咱们没有这个，不知道是说明需求，可以说明下。

**Comment by wubodanran** [comment]
像这样的：
![image](https://user-images.githubusercontent.com/29586966/40893450-c5df3f8c-67d3-11e8-8684-d0d8a0833adb.png)

**Comment by chenxuan0000** [comment]
@wubodanran  我懂你的意思了，你是想我再每个滚动事件进入或者离开，增加个emit事件给父元素是吗？

**Comment by chenxuan0000** [comment]
@wubodanran  不是很明白你是意思，你可以把源码拉到自己的项目，改写尝试下。
