### ISSUE TITLE
请增加刷新率适配

### ISSUE THREAD

**Issue by qhdhiman** [chenxuan0000/vue-seamless-scroll#160]
出现的问题：目前速度是按照60次/s计算的，在低于这个刷新率的电脑上滚动速度会变慢，高于这个刷新率的电脑上会变快。

具体操作请参考：https://developer.mozilla.org/zh-CN/docs/Web/API/Window/requestAnimationFrame

**Comment by chenxuan0000** [comment]
@qhdhiman 是基于requestAnimationFrame来做的滚动。
需要再不同的刷新率下适配建议自行算下FPS，设置对应step。
https://www.cnblogs.com/coco1s/p/8029582.html
