### ISSUE TITLE
滚动到到最后会出现空白部分.

### ISSUE THREAD

**Issue by wubodanran** [chenxuan0000/vue-seamless-scroll#17]
如图：![image](https://user-images.githubusercontent.com/29586966/40832277-96c604b4-65bd-11e8-93b4-a7c0007a0801.png)

![image](https://user-images.githubusercontent.com/29586966/40832309-a3f0f680-65bd-11e8-9c54-cf572e1751df.png)
部分源码：
![image](https://user-images.githubusercontent.com/29586966/40832379-c1915040-65bd-11e8-98fe-56efb97f8dda.png)

![image](https://user-images.githubusercontent.com/29586966/40832436-e9795026-65bd-11e8-8e31-789baae300f9.png)

**Comment by chenxuan0000** [comment]
@wubodanran  有没有设置外层的限制宽度，左右滚动的ul宽度需要手动设置下。如果都设置了，不应该会有这个问题。

**Comment by chenxiaobin** [comment]
同样有这样的问题，ul的内容可能很多，我不知道具体宽度是多少，都是撑开的，设置了固定宽度内容会被截掉的
