### ISSUE TITLE
与多个echarts在同一页面会导致卡顿

### ISSUE THREAD

**Issue by duoduoele** [chenxuan0000/vue-seamless-scroll#176]
经过测试，只有在1~2个echarts图表的时候才不会卡，多了就会导致卡顿。。http://aduele.cn/btc/这是测试网址

**Comment by chenxuan0000** [comment]
https://chenxuan0000.github.io/vue-seamless-scroll/zh/guide/09-echart.html

多个简单的Echart，并不会卡顿明显。 如果真卡
1、Echart复杂数据量大，数量多，单单使用Echart也会有卡顿
2、尝试关闭Echart动画，采样或者其他手段减少数据量
