### ISSUE TITLE
窗口缩放时，容器宽度没重新计算，导致滚动项溢出

### ISSUE THREAD

**Issue by zhoudaxiaa** [chenxuan0000/vue-seamless-scroll#183]
当从小窗口，放大到大窗口时，容器的宽度没有重新计算，导致内部的滚动项宽度超出容器。建议加个滚动监听，reset 下

**Comment by chenxuan0000** [comment]
resize时候更新配置项autoPlay，或者手动调用vue-seamless-scroll中reset方法即可。
