### ISSUE TITLE
是否有插件形式的调用支持？

### ISSUE THREAD

**Issue by cdswyda** [chenxuan0000/vue-seamless-scroll#2]
无缝滚动，能否直接以插件的形式来使用呢？

这样在需要用无缝滚动的时候，我就不用单独为这个区域再创建一个组件了。

请轩大神支持下！

**Comment by cdswyda** [comment]
@chenxuan0000

**Comment by chenxuan0000** [comment]
@cdswyda 
new seamlessScroll(this,$refs.abc,this.options)  like this？
我认为，这样组件带solt的方式更接地气啊

**Comment by fengcms** [comment]
很好的一个小组件，建议首页的说明文档再详细一点，我稍微研究了一下才会使用的。

**Comment by chenxuan0000** [comment]
@fengcms ok 我会抽空完善下顺便再加个中文文档
