### ISSUE TITLE
列表循环两遍

### ISSUE THREAD

**Issue by zhao-yang857** [chenxuan0000/vue-seamless-scroll#206]
作者你好，我不知道为什么这个插件默认循环两个列表（我只循换了一个默认的data数组），但是列表循环了两遍，正常来说是循换一个列表，然后让这个列表里面的数据自己滚动，请问这个怎么改呢？

<img width="381" alt="912e6db6b17d727dd3f05b1aacefede" src="https://user-images.githubusercontent.com/74173392/202157553-25a5cf3e-b7a5-49ad-9634-8b20356f000a.png">

**Comment by chenxuan0000** [comment]
@zhao-yang857 这是组件内部 克隆的一份， 实现无缝衔接滚动一种思路。

**Comment by zhao-yang857** [comment]
那请问怎么把这克隆的一份去掉呢  我不需要这块
