### ISSUE TITLE
无法自动滚动，除非鼠标悬停再移开

### ISSUE THREAD

**Issue by szagnesc** [chenxuan0000/vue-seamless-scroll#21]
optionSingleHeight() {
            return {
                step: 2,
                switchDelay: 0,
                limitMoveNum:7,
                hoverStop: true,
                direction: 1,
                openWatch: false,
                singleHeight: 100 
            };
        }

以上是配置项，但是进入页面的时候不会自动滚动，要先把鼠标挪上去，再移开，才会滚动。请问是配置有什么问题吗。谢谢

**Comment by chenxuan0000** [comment]
@szagnesc  你这个配置我本地试过可以没有问题的。
