### ISSUE TITLE
刷新页面,马上就滚动了,能不能延迟1秒钟呢

### ISSUE THREAD

**Issue by zhulibin2012** [chenxuan0000/vue-seamless-scroll#22]

**Comment by Tomar-Y** [comment]
刷新就控制的没有，你可以暂时通过其他方式实现下。
   
   
   ------------------------原始邮件------------------------  
   
   发信人：zhulibin2012<notifications@github.com> 
   时间：07:45:16 下午 
   收信人：chenxuan0000/vue-seamless-scroll<vue-seamless-scroll@noreply.github.com> 
   抄送：Subscribed<subscribed@noreply.github.com> 
   标题：[chenxuan0000/vue-seamless-scroll] 刷新页面,马上就滚动了,能不能延迟1秒钟呢 (#22)

**Comment by chenxuan0000** [comment]
@Tomar-Y  tk  @zhulibin2012  
![image](https://user-images.githubusercontent.com/23030433/43700532-8b75caee-9985-11e8-9b5d-57097b65a68f.png)
