### ISSUE TITLE
可以提供一个钩子点击时返回当前显示的那一条的index吗

### ISSUE THREAD

**Issue by indown** [chenxuan0000/vue-seamless-scroll#24]
现在第一条是点不到的，可以提供一个钩子点击时返回当前显示的那一条的index吗

**Comment by xiaoxiaoxiaoyang** [comment]
单行停顿 singleHeight   只显示一条的情况下

**Comment by chenxuan0000** [comment]
@xiaoxiaoxiaoyang  单行停顿，可视区域一条？ 然后单词停顿后，emit出去一个事件吗？

**Comment by xiaoxiaoxiaoyang** [comment]
@chenxuan0000 抱歉，没有及时看到你的回复，我是用a标签的href满足了需求，谢谢
