### ISSUE TITLE
我用了楼主的，方法写的无缝滚动，但是滚动后，里面的内容 有的点击无效，有的能点击上，这是什么原因呢

### ISSUE THREAD

**Issue by zfleaves** [chenxuan0000/vue-seamless-scroll#25]

**Comment by chenxuan0000** [comment]
@zfleaves  组件内部复制的是简单复制，没有复制事件。 需要的话看下项目的readme我有给出临时解决方案。手动复制下事件。

**Comment by chenxuan0000** [comment]
https://github.com/chenxuan0000/vue-seamless-scroll/blob/master/issuses/problem1.md  @zfleaves
