### ISSUE TITLE
在nuxt.js中有警告怎么解决？

### ISSUE THREAD

**Issue by chenjiecloud** [chenxuan0000/vue-seamless-scroll#28]
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

**Comment by Brolly0204** [comment]
解决了？？？ 想知道解决方案
