### ISSUE TITLE
容器内li的点击事件

### ISSUE THREAD

**Issue by gr510071555** [chenxuan0000/vue-seamless-scroll#31]
需要给容器内的li绑定点击事件，但是复制的li没有办法绑定，怎么解决

**Comment by frankfang7** [comment]
可以给个demo么？

**Comment by frankfang7** [comment]
这个有没有demo可供参考的？

**Comment by chenxuan0000** [comment]
@frankfang7 事件代理，给父元素绑定对应事件，在需要的子元素上进行事件补获。js原生事件代理。不清楚可以查下如何写。
