### ISSUE TITLE
cpu带不起你的程序

### ISSUE THREAD

**Issue by wwwhehehe** [chenxuan0000/vue-seamless-scroll#34]
我mac开发只要切换到有引入你的vue-seamless-scroll的组件，马上cpu像疯了一样，温度慢慢飙升，直接到99度。不是夸张。希望大佬你能检查一下你的代码看看哪里是否还能优化。不能完成功能就忽略了性能问题

**Comment by zhuyuhaoliar** [comment]
我也是一样。。。。

**Comment by chenxuan0000** [comment]
@wwwhehehe @zhuyuhaoliar  什么浏览器，我这没有发热情况。

**Comment by wwwhehehe** [comment]
用 style="transform: translate3d()"  谷歌浏览器，打开谷歌开发者模式cpu温度提升比较明显

**Comment by wwwhehehe** [comment]
![image](https://user-images.githubusercontent.com/37824820/47698371-0d157200-dc4a-11e8-9ff9-ce0df90390a2.png)

**Comment by wwwhehehe** [comment]
我看了jquery.marquee 他写的没有去不断操作translate
![image](https://user-images.githubusercontent.com/37824820/47698642-1a7f2c00-dc4b-11e8-933a-6549a4f60990.png)

**Comment by heguofeng** [comment]
内存一直在涨  放了两三个小时 chrome占了4000MB的内存，可能是代码有什么问题哦

**Comment by chenxuan0000** [comment]
@wwwhehehe  jquery.marquee是直接根据配置生成的animation用css3来实现的滚动，不支持单步停留。
这里是用的requestAnimationFrame来实现的定时改变transform。
一直再改变会导致页面的重排和重绘，所以用tranform方式没有用left，right来GPU加速，这样必然会有部分的浏览器内存消耗。
@heguofeng 但是没有那么夸张。也行你用的不是我给出的simple demo页面看的？
![image](https://user-images.githubusercontent.com/23030433/51155382-43aa7280-18b2-11e9-8cf3-34d822221399.png)
页面开启停留30分钟的截屏。

**Comment by ricekyan** [comment]
有优化的方法吗？切换到其他页面定时器还在跑

**Comment by ricekyan** [comment]
内存一直下不去

**Comment by ytxDaXiong** [comment]
me too CPU飙到100% 内存一直增加  还没看源码 不知道什么 原因
