### ISSUE TITLE
单行滚动，内容始终无法滚到正中间

### ISSUE THREAD

**Issue by mayqiyue** [chenxuan0000/vue-seamless-scroll#35]
get classOption() {
    return {
      step: 1,
      singleHeight: 1,
      isSingleRemUnit: true,
      limitMoveNum: this.scrollList.length,
      openTouch: false,
      waitTime: 2000
    };
  }

**Comment by wjhcc2018** [comment]
我也遇到了这个问题

**Comment by mayqiyue** [comment]
我已经弃库了，，
