### ISSUE TITLE
设置向右横向滚动条，外部盒子一直有一个750px的默认值限制内容显示

### ISSUE THREAD

**Issue by ChazLun** [chenxuan0000/vue-seamless-scroll#37]
![image](https://user-images.githubusercontent.com/22490984/48245881-16f85b80-e428-11e8-984c-23343f68dba5.png)
![image](https://user-images.githubusercontent.com/22490984/48245897-34c5c080-e428-11e8-885f-f450eb5c22bc.png)

**Comment by chenxuan0000** [comment]
@ChazLun 左右的滚动不是很好用，你给ul设置css width，外层会计算需要的warp宽度。你的最外层需要在往外一层。
![image](https://user-images.githubusercontent.com/23030433/48552354-52f15c00-e913-11e8-9331-9af5b4ee8653.png)

**Comment by ChazLun** [comment]
好的，谢谢，我去尝试一下
