### ISSUE TITLE
setp 参数设置不起作用

### ISSUE THREAD

**Issue by KuangPF** [chenxuan0000/vue-seamless-scroll#4]
在`vue`中配置step参数，貌似没有起作用，设置成1或者100 或者0 滚动速度没变

**Comment by chenxuan0000** [comment]
从未发现有这个问题呢 我的在线demo里面有这个配置的事例你可以看下  你那实现不行请给出在线调试地址

**Comment by chenxuan0000** [comment]
@KuangPF   https://chenxuan0000.github.io/component-document/index_prod.html#/component/seamless-others

**Comment by KuangPF** [comment]
我今天再设置了一下参数，起作用了，可能当天哪里设置错了，然后没太注意，谢谢楼主了。另外不知道这个功能有没有考虑过：如果每一行的高度不一样，在进行向上或者向下滚动时，不知道单行停留这个功能还能用不

**Comment by chenxuan0000** [comment]
这个需求需求没考虑过 就算能实现成本也很好
