### ISSUE TITLE
table表格的滚动，会遍历两次数据，自动遍历的css样式丢失，请问怎样解决

### ISSUE THREAD

**Issue by wcy19961209521** [chenxuan0000/vue-seamless-scroll#40]
<vue-seamless-scroll :data="table.messages"  style="overflow:hidden;  height:100%;">
          <tr v-for="(item,index) in table.messages" :key="index">
            <td>{{index+1}}</td>
            <td v-for=" items in item.message">{{items}}</td>
          </tr>
      </vue-seamless-scroll>、
请问哪里有错误？会遍历两次数据

**Comment by wcy19961209521** [comment]
<vue-seamless-scroll :data="table.messages"  style="overflow:hidden;  height:100%;">
          <tr v-for="(item,index) in table.messages" :key="index">
            <td>{{index+1}}</td>
            <td v-for=" items in item.message">{{items}}</td>
          </tr>
      </vue-seamless-scroll>、
请问哪里有错误？会遍历两次数据

**Comment by chenxuan0000** [comment]
@wcy19961209521  请提供下demo代码。

**Comment by wcy19961209521** [comment]
> @ wcy19961209521 请提供下演示代码。

 <vue-seamless-scroll :data="table.messages"  style="overflow:hidden;  height:100%;">
          <tr v-for="(item,index) in table.messages" :key="index">
            <td>{{index+1}}</td>
            <td v-for=" items in item.message">{{items}}</td>
          </tr>
      </vue-seamless-scroll>、
请问哪里有错误？会遍历两次数据
