### ISSUE TITLE
建议加上一个判断，当数据条数不足盒子高度的时候，所有的参数置空，不参加滚动

### ISSUE THREAD

**Issue by zhenggaowei** [chenxuan0000/vue-seamless-scroll#41]
建议加上一个判断，当数据条数不足的时候，所有的参数置空，不参加滚动

**Comment by chenxuan0000** [comment]
@zhenggaowei  外层高度是由你们自己来设定的。如果有这个需要可以在外层控制一下。

**Comment by zhenggaowei** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    一个地方用到的话自己写还是可以的，如果一个页面的多个地方用到还是写在组件内部比较好！
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                z.gecko
                            
                    
                        
                            
                                    z.gecko@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年01月4日 09:50，sos<notifications@github.com> 写道： 


@zhenggaowei  外层高度是由你们自己来设定的。如果有这个需要可以在外层控制一下。



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by chenxuan0000** [comment]
@zhenggaowei  使用这个参数控制 limitMoveNum 开启无缝滚动的最小数据量
@zhenggaowei 因为外层的warp和 里层的item的高度都是需要获取的，这里自行控制更加妥善。

**Comment by cqh-sy** [comment]
当屏幕缩小的时候，条件满足滚动条件，我limitMoveNum等于数据量，，这时，我伸展屏幕（已经不满足滚动条件了，我设置limitMoveNum大于数据量），它还滚动，是什么原因呢？
