### ISSUE TITLE
在页面缓存的情况下，从子路由跳转回去，无法滚动

### ISSUE THREAD

**Issue by Damon-duan** [chenxuan0000/vue-seamless-scroll#48]
在页面缓存的情况下，首次加载页面滚动效果是正常的，点击发生跳转到子路由，从子路由跳转回去，无法再滚动。

**Comment by chenxuan0000** [comment]
@Damon-duan keep-alive页面缓存路由跳转组件报错的问题，早期版本已经解决，如果不是这个问题请说明下。
