### ISSUE TITLE
在做自适应网页的时候用的rem单位

### ISSUE THREAD

**Issue by yaphetsnjn** [chenxuan0000/vue-seamless-scroll#5]
请问用rem设置singleHeight如何才能生效。

**Comment by chenxuan0000** [comment]
@yaphetsnjn 用了rem你只能把当前页面的基准的font-size和当前rem值得出结果赋值，或者简单点列表高度不要用rem。

**Comment by chenxuan0000** [comment]
@yaphetsnjn  可以提个pr加个参数，singleHeightRem 传入rem的数值里面取html的font-size处理下。
