### ISSUE TITLE
第二次加载缓慢，内容有空白时间较长

### ISSUE THREAD

**Issue by cenjiaxiang** [chenxuan0000/vue-seamless-scroll#52]
第一次滚动正常（以为一开始还没有滚动之前，就是看到第一块数据块），第二次滚动，第一块数据加载缓慢（我的数据块比较多内容，有echart图），请问，是否可以设置，第二次滚动的时候，不需要重新加载呢？

**Comment by cenjiaxiang** [comment]
环境是，vue-cli@~3.0以上，

**Comment by chenxuan0000** [comment]
@cenjiaxiang 你这里的第二次滚动是什么意思？ 如果有echart图表建议先图表加载完成后再滚动。加载echarts会阻塞ui。

**Comment by cenjiaxiang** [comment]
@chenxuan0000 第二次滚动，意思是： 自动无缝滚动，全部内容第一次全部滚完上去了，第二次从头开始，echart要等到，第一次全部滚完以后才会加载echart图，我的需求可能稍稍有些奇葩，主要是：需要是显示的区域比较特别。有时间的话，我给你发个demo吧，谢谢解答

**Comment by ChenYCL** [comment]
@cenjiaxiang 解决了么，同问题

**Comment by cenjiaxiang** [comment]
> @cenjiaxiang 解决了么，同问题

你好，问题找出来了，是因为无缝滚动会在前后加载两个相同的，而echart需要唯一id加载数据，所有，暂时实现不了带有echart图的无缝滚动，我也试过swipe插件，也是同样的问题，希望对你有帮助

**Comment by ChenYCL** [comment]
@cenjiaxiang 我是正常的li列表用的demo跑的，再切换的时候能看到空白，大概是copyHtml的那一瞬间

**Comment by cenjiaxiang** [comment]
@ChenYCL 那我们的情况大概不同，你看下，是否需要在切换的时候，判断list 长度大于0，在去加载无缝滚动，是否会解决？

**Comment by ChenYCL** [comment]
@cenjiaxiang 偶尔情况下一个布局导致这个问题，当父容器display：flex，滚动容器高度为100%时，会随着滚动方向，容器高度变小，但复制的html插入的位置仍然是之前父容器100%高度的下方，空白就产生了，比较玄学，

**Comment by chenxuan0000** [comment]
@ChenYCL 注意下文档，最外层warp容器的宽高要设置，并且overflow：hidden。不清楚复制demo里面的代码调试看看。

**Comment by meiyuesheng** [comment]
也遇到同样的问题，无缝滚动时，组件复制的包含echart的内容不能渲染，把echart 渲染模式从svg换成canvas就行了
