### ISSUE TITLE
step: 属性设置为0.5以下的小数点，向上滚动有卡顿的晃动效果

### ISSUE THREAD

**Issue by cenjiaxiang** [chenxuan0000/vue-seamless-scroll#53]
step: 属性设置为0.5以下的小数点，
由于向上滚动的频率要求非常慢，设置了step为小数点，数据块向上移动的时候，向上滚动有卡顿的晃动效果,还是因为自己的一条数据块太多的原因导致的呢？

**Comment by chenxuan0000** [comment]
@cenjiaxiang  https://jsfiddle.net/ 提供个在线的demo，或者发至我邮箱 xuan.chen@ximalaya.com

**Comment by 632611768** [comment]
translate改成translate3d好像不卡顿，更多机型没测试过，安卓下是卡顿的

**Comment by LeeRHuang** [comment]
我也发现有卡顿
