### ISSUE TITLE
第一次把内容滚动完后，需要等一段空白才会重复滚动内容

### ISSUE THREAD

**Issue by ganyiak** [chenxuan0000/vue-seamless-scroll#55]

**Comment by ganyiak** [comment]
![image](https://user-images.githubusercontent.com/38201383/56945603-4c217300-6b5a-11e9-82f9-b288ba400bb6.png)

**Comment by chenxuan0000** [comment]
<template>
    <vue-seamless-scroll :data="newsList" :class-option="optionLeft" class="seamless-warp2">
        <ul class="item">
            <li v-for="item in newsList" v-text="item.title"></li>
        </ul>
    </vue-seamless-scroll>
</template>
<style lang="scss" scoped>
    .seamless-warp2 {
        overflow: hidden;
        height: 25px;
        width: 380px;
        ul.item {
            width: 580px;
            li {
                float: left;
                margin-right: 10px;
            }
        }
    }
</style>
<script>
    export default {
        data () {
            return {
                newsList: [{
                      'title': 'A simple, seamless scrolling for Vue.js'
                    }, {
                      'title': 'A curated list of awesome things related to Vue.js'
                    }]
                 }
            },
            computed: {
                optionLeft () {
                    return {
                            direction: 2,
                            limitMoveNum: 2
                        }
                }
             }
       }
</script>
@ganyiak 参考下这个，如果还有问题贴下实例代码

**Comment by c1026287787** [comment]
我也遇到这样的问题了，贴上gif图

![avatar](https://edocument-flashclaim.chinalife-q.com/FLASHCLAIM/EMPLOYER/8888/CLAIM/201907/300420190628093405088798/DISABILITY_RATING_CERTIFICATE/c4760f27-2045-4eca-b5e1-bba3be349f43.gif)

**Comment by c1026287787** [comment]
@chenxuan0000

**Comment by chenxuan0000** [comment]
@ganyiak 提供下的你配置

**Comment by c1026287787** [comment]
@chenxuan0000 

classOption () {
			return {
				step: 0.2, //数值越大速度滚动越快
				limitMoveNum: this.listData.length, //开始无缝滚动的数据量
				hoverStop: true, //是否开启鼠标悬停stop
				direction: 1, // 0向下 1向上 2向左 3向右
				openWatch: true, //开启数据实时监控刷新dom
				singleHeight: 0, //单步运动停止的高度(默认值0是无缝不停止的滚动) direction => 0/1
				singleWidth: 0, //单步运动停止的宽度(默认值0是无缝不停止的滚动) direction => 2/3
				waitTime: 1000 //单步运动停止的时间(默认值1000ms)
			}
		}

**Comment by yundingy** [comment]
我也遇到这样的问题，如果滚动的是页面写死的内容就没问题，如果使用v-for循环出来的就会有上面的bug

**Comment by lxiaojin** [comment]
我也遇到了。。。。难搞

**Comment by ganyiak** [comment]
这个好像是和滚动容器的宽度有关系




| |
15658025680
邮箱：15658025680@163.com
|

Signature is customized by Netease Mail Master

在2019年08月15日 10:04，lxiaojin 写道：

我也遇到了。。。。难搞

**Comment by lxiaojin** [comment]
那应该怎么解决呢。。盒子的宽度是 elmentui 的栅格布局



------------------ 原始邮件 ------------------
发件人: "ganyiak"<notifications@github.com>; 
发送时间: 2019年8月15日(星期四) 下午2:41
收件人: "chenxuan0000/vue-seamless-scroll"<vue-seamless-scroll@noreply.github.com>; 
抄送: "罗颜金"<1017908262@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [chenxuan0000/vue-seamless-scroll] 第一次把内容滚动完后，需要等一段空白才会重复滚动内容 (#55)



这个好像是和滚动容器的宽度有关系
 
 
 
 
 | |
 15658025680
 邮箱：15658025680@163.com
 |
 
 Signature is customized by Netease Mail Master
 
 在2019年08月15日 10:04，lxiaojin 写道：
 
 我也遇到了。。。。难搞

**Comment by chenxuan0000** [comment]
https://github.com/chenxuan0000/vue-seamless-scroll/blob/master/document/README.md#%E4%B8%AA%E5%88%AB%E7%89%B9%E6%AE%8A%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E
