### ISSUE TITLE
数据是动态的，总宽度不够，应该是3600px 实际上只有1800px, 尽管有float:left; 不过也挤下来了。

### ISSUE THREAD

**Issue by yuanxianjun** [chenxuan0000/vue-seamless-scroll#57]
![image](https://user-images.githubusercontent.com/29246899/59421836-db7ca000-8e01-11e9-867b-89ab84571827.png)
![image](https://user-images.githubusercontent.com/29246899/59422463-03b8ce80-8e03-11e9-9aa0-e1d9e664163e.png)

**Comment by 1049612128** [comment]
我也遇到这个问题了。如何解决

**Comment by seayao** [comment]
#63

**Comment by chenxuan0000** [comment]
@seayao 3q我下个版本给出解决方案

**Comment by chenxuan0000** [comment]
1.1.17已经修复
