### ISSUE TITLE
滚动停止的时候点击事件没有添加上去，但滚动开始了之后点击事件又添加进去了。

### ISSUE THREAD

**Issue by zuozuolovegit** [chenxuan0000/vue-seamless-scroll#59]

**Comment by zhdanny** [comment]
我也遇到了这个问题

**Comment by WangSenkai** [comment]
你们解决了吗？

**Comment by chenxuan0000** [comment]
@zuozuolovegit @zhdanny @WangSenkai 
Version（版本号）

Steps to reproduce（复现步骤）

What is expected? （期望效果）

What is actually happening? （目前现状描述）

完成后重新打开issue
