### ISSUE TITLE
不支持点击

### ISSUE THREAD

**Issue by mrzhou321** [chenxuan0000/vue-seamless-scroll#6]
深复制的时候 点击事件没有复制过去， 总有视图大小范围里的控件点击动作无效

**Comment by chenxuan0000** [comment]
@mrzhou321 可否 给出复现方法  在线调试地址也行

**Comment by chenxuan0000** [comment]
@mrzhou321  我懂你的意思了 我抽空处理下吧

**Comment by chenxuan0000** [comment]
@mrzhou321  今天看了下 我里面只是进行了简单的innerHtml的拷贝 并没有进行类似jq clone(true)的深层的连带事件的拷贝。一般来说无缝滚动列表最多是个链接 可以用a标签解决。
