### ISSUE TITLE
:class-option接口失效了？

### ISSUE THREAD

**Issue by Guanrui1** [chenxuan0000/vue-seamless-scroll#60]
:class-option接口失效了？

**Comment by chenxuan0000** [comment]
@Guanrui1 贴下配置代码截图。

**Comment by chenxuan0000** [comment]
@Guanrui1 
Version（版本号）

Steps to reproduce（复现步骤）

What is expected? （期望效果）

What is actually happening? （目前现状描述）

完成后重新打开issue
