### ISSUE TITLE
能否提供下li点击事件的有效demo

### ISSUE THREAD

**Issue by MaybeQHL** [chenxuan0000/vue-seamless-scroll#61]
目前需求需要滚动复制的dom也需要事件。按照事件代理方法 点击dom后会掉二次事件。怎么才能解决呢

**Comment by MaybeQHL** [comment]
昨天自己研究了一下解决了。在掘金写了文章 地址：https://juejin.im/post/5d1c1cd96fb9a07ef2013c56

**Comment by chenxuan0000** [comment]
@MaybeQHL  👍
