### ISSUE TITLE
垂直从上往下轮播，渲染多行数据，绑定在第一条数据的@click事件，为什么不生效？

### ISSUE THREAD

**Issue by MrDuFei** [chenxuan0000/vue-seamless-scroll#62]
<vue-seamless-scroll :data="dymamciList" class="seamless-warp" :class-option="classOption">
     <li v-for="(item, index) in dymamciList" :key="index">
             <a @click='toDetail'>{{item.title}}</a>
     </li>
</vue-seamless-scroll>
点击第一个渲染的a标签，不生效。

**Comment by MrDuFei** [comment]
<vue-seamless-scroll :data="dymamciList" class="seamless-warp" :class-option="classOption">
       <li v-for="(item, index) in dymamciList" :key="index">
          <a @click='toDetail(item)'>{{item.title}}</a>
        </li>
</vue-seamless-scroll>

**Comment by MrDuFei** [comment]
`<vue-seamless-scroll :data="dymamciList" class="seamless-warp" :class-option="classOption">
                        <li v-for="(item, index) in dymamciList" :key="index">
                            <a @click=‘toDetail(item)’>{{item.title}}</a>
                        </li>
                    </vue-seamless-scroll>`

**Comment by chenxuan0000** [comment]
https://github.com/chenxuan0000/vue-seamless-scroll/blob/master/issuses/problem1.md
@MrDuFei 暂时这么处理绑定事件问题

**Comment by chenxuan0000** [comment]
@MrDuFei https://juejin.im/post/5d1c1cd96fb9a07ef2013c56

**Comment by chenxuan0000** [comment]
@MrDuFei https://juejin.im/post/5d1c1cd96fb9a07ef2013c56
