### ISSUE TITLE
左右滚动时。li的宽度不定。无法写死width.导致宽度不够。2个ul不在同一水平上。播放完一次后空白很大

### ISSUE THREAD

**Issue by 1049612128** [chenxuan0000/vue-seamless-scroll#63]

**Comment by seayao** [comment]
1、无法写死宽度的解决方案：
li不要用float布局，ul用flex布局，
这样wrap和ul的宽度就可以设置为100%，
2、播放完一次后空白很大：
我猜作者是为了监听ScrollEnd事件，所以说没有做那种左边快要（还有一定宽度）滚动完，右边立马补上来的效果，目前我的解决方案是在ul上加一个margin-left: 值自行设定；效果会稍微好点，不至于很突兀。
我真是个小机灵鬼，这样的问题我都能想到解决方案。
（^_−）

**Comment by chenxuan0000** [comment]
@seayao @1049612128 
1. 无法写死宽度的解决方案：只需要slot那个dom设置为flex即可。
2. 播放完一次后空白很大，我猜是offsetWidth四舍五入bug导致的下个版本修复了。

**Comment by chenxuan0000** [comment]
1.1.17文档中有说明了
