### ISSUE TITLE
两行不一行上，会出现空白

### ISSUE THREAD

**Issue by wyulang** [chenxuan0000/vue-seamless-scroll#64]
两行不一行上，会出现空白，建议改变下就行了，
const w = this.$refs.slotList.offsetWidth * rate +2
因为offsetWidth出现小数点的情况会4舍5入，当小0.5时就会出现两行，所以加个2，就解决了

**Comment by chenxuan0000** [comment]
@wyulang 谢谢提醒，下版本近期发布一并修复

**Comment by chenxuan0000** [comment]
1.1.17已经修复
