### ISSUE TITLE
对几千条的数据滚动有什么优化建议？

### ISSUE THREAD

**Issue by DengRiGuang** [chenxuan0000/vue-seamless-scroll#65]
数据量大的时候，页面很明显感觉到卡顿，页面上其他事件也会收到其影响

**Comment by chenxuan0000** [comment]
@DengRiGuang 几千条数据的单纯全部静态展示再网页上都会感觉卡，不推荐做滚动了。
如果需要做只能考虑再页面上只展示个100多条，其他再对应的时机插队队尾，前面的移出。
目前插件不支持你这种的需求。
