### ISSUE TITLE
新功能能否增加不重复数据功能 

### ISSUE THREAD

**Issue by well-monkey** [chenxuan0000/vue-seamless-scroll#66]
类似效果 见 http://www.dowebok.com/demo/188/index6.html

非无缝滚动  可以悬停 但是数据不重复

**Comment by chenxuan0000** [comment]
@well-monkey 看到了，里面没有重复一次，可否说下应用场景，最近两个月会优化下代码，加下新配置。

**Comment by well-monkey** [comment]
应用场景是这样的：
有一个开奖列表 实时websocket在推送 新数据  会有源源不断的新的结果在列表上面展示。
而且这些开奖结果不重复，也就是我给链接的那个地址。
我找了一下类似的应用场景。找到了一个类似的应用场景 链接是这个 https://eosplay.com/lottery 
一进页面就能看到右侧的数据不重复的非无缝滚动 可悬停效果

**Comment by chenxuan0000** [comment]
@well-monkey  看了这种需求如果数据量不是很大完全可以自己自己写个定时器实现了，css也行。
如果数据量大还得考虑把溢出的部分数据清除，防止浏览器卡死。
这个组件一般是用作数据量较少的无缝滚动的。
建议个vue-awesome上找找有没有类似的滚动库。
https://github.com/vuejs/awesome-vue
