### ISSUE TITLE
有没有停止滚动事件？ 和再次开始滚动事件

### ISSUE THREAD

**Issue by adevin** [chenxuan0000/vue-seamless-scroll#68]

**Comment by chenxuan0000** [comment]
暂不支持，如果非要这个需求，
1. 可以通过直接修改组件内data上的isHover为true实现，会拦截接下来所有的滚动。
2. 如果要再次开始首先把他重置为false，然后在调用下_move事件。
在父组件 this.$refs.组件ref.属性/方法来修改。

**Comment by huainanhai** [comment]
> 暂不支持，如果非要这个需求，
> 
> 1. 可以通过直接修改组件内data上的isHover为true实现，会拦截接下来所有的滚动。
> 2. 如果要再次开始首先把他重置为false，然后在调用下_move事件。
>    在父组件 this.$refs.组件ref.属性/方法来修改。

not work

**Comment by chenxuan0000** [comment]
this.$refs.组件ref._startMove()
this.$refs.组件ref._stopMove()
