### ISSUE TITLE
当数据的长度为后端传来时，动态绑定 :style=“{width: 单个元素width * data.length}”时无效

### ISSUE THREAD

**Issue by honestfat** [chenxuan0000/vue-seamless-scroll#7]
后端传过来的图片长度不固定，就想为父级元素绑定一个动态style的宽度。结果无效

**Comment by chenxuan0000** [comment]
@honestfat  已经修复 尝试下 1.1.10的版本,组件里面会监听data的变化，后端接口返回数据会watch到重新计算目前的宽度，应该是可以了。
