### ISSUE TITLE
停顿时间错误

### ISSUE THREAD

**Issue by angrydog666** [chenxuan0000/vue-seamless-scroll#71]
在钉钉开发中引入，设置了停顿时间，正常滚动一两分钟后，停顿时间变得特别长，

**Comment by chenxuan0000** [comment]
@angrydog666 是否项目里面存在阻塞等情况

**Comment by chenxuan0000** [comment]
@angrydog666 
Version（版本号）

Steps to reproduce（复现步骤）

What is expected? （期望效果）

What is actually happening? （目前现状描述）

完成后重新打开issue
