### ISSUE TITLE
能不能分页数据切换的时候能进行无缝滚动啊

### ISSUE THREAD

**Issue by qiugu** [chenxuan0000/vue-seamless-scroll#75]
现在的需求是展示的数据是请求接口，分页获取的数据，每次展示完第一页数据后，再展示第二页，以此类推，到最后一页的时候，跳转回第一页，但是切换页面的时候，会出现滚动到中间的时候，下面半截是空的
![图片](https://user-images.githubusercontent.com/33192247/65292639-c0e95e00-db8a-11e9-8155-0ada22588341.png)

**Comment by qiugu** [comment]
已解决，调整高度就可以

**Comment by qurge** [comment]
> 已解决，调整高度就可以

大佬咋解决的？
