### ISSUE TITLE
我动态设置了外部容器的宽度，如何触发组件内部重新计算自己的宽度呢？

### ISSUE THREAD

**Issue by mrsai** [chenxuan0000/vue-seamless-scroll#77]

**Comment by chenxuan0000** [comment]
组件v-if，尝试下设置完宽度在放开组件的v-if状态。

**Comment by chenxuan0000** [comment]
https://github.com/chenxuan0000/vue-seamless-scroll/blob/master/document/README.md#%E4%B8%AA%E5%88%AB%E7%89%B9%E6%AE%8A%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E
