### ISSUE TITLE
浏览器兼容

### ISSUE THREAD

**Issue by yuanxianjun** [chenxuan0000/vue-seamless-scroll#83]
chrome 78 的版本是否兼容，现在碰到的问题是正常横向滚动的内容，走一段时间突然就消失了
再过一段时间自己又显示出来了

**Comment by chenxuan0000** [comment]
@yuanxianjun 
https://github.com/chenxuan0000/vue-seamless-scroll/blob/master/document/README.md#%E4%B8%AA%E5%88%AB%E7%89%B9%E6%AE%8A%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E
