### ISSUE TITLE
当数据重新轮播到第一条时，会打乱样式

### ISSUE THREAD

**Issue by shisanOnly** [chenxuan0000/vue-seamless-scroll#86]
![20191112-224300_capture](https://user-images.githubusercontent.com/35761035/68681590-9de19600-059e-11ea-9501-34106afc184d.gif)
环境：
vue：2.6.10
vue-seamless-scroll：1.1.17
测试数据有6条

**Comment by shisanOnly** [comment]
当第一条数据回到顶部时，样式又正常了

**Comment by chenxuan0000** [comment]
@shisanOnly 
Version（版本号）

Steps to reproduce（复现步骤）

What is expected? （期望效果）

What is actually happening? （目前现状描述）

完成后重新打开issue，补全下，复现方法
