### ISSUE TITLE
能不能把_initMove里的width干掉，或者开个口出来

### ISSUE THREAD

**Issue by acegank** [chenxuan0000/vue-seamless-scroll#89]
实际加了这个宽度后，导致宽度加长了，部分显示不对了

**Comment by acegank** [comment]
上下滚动的时候，wrap其实不用再去计算宽度，默认父节点宽度即可

**Comment by ZedCoding** [comment]
![image](https://user-images.githubusercontent.com/24578758/70587203-4cabdd00-1c04-11ea-853d-2c4c874ef38e.png)
 duid
width其实是不需要的 现在想去掉都挺麻烦

**Comment by chenxuan0000** [comment]
fixed
