### ISSUE TITLE
列表第一项无法点击，加载页面时快速滚动走了，希望大大可以提供下解决方法！！

### ISSUE THREAD

**Issue by yukaihua1997** [chenxuan0000/vue-seamless-scroll#93]
classOption () {
				return {
					singleHeight: this.lineHeight,
					waitTime: 5,
					limitMoveNum: 3,
					step: 1,
					hoverStop: true
				};
			}
配置如上，列表第一项不能触发点击事件；只有当autoPlay为false时，才可以点击列表第一项；
另外，加载页面时，列表第一项飞速就滚动上去了，没有停留；
希望大大可以提供下解决方法！！

**Comment by yukaihua1997** [comment]
你可以在你的demo5上加个click事件看看，一点第一项就不触发，第一项之后的点击也不触发，第一项之前的点击才会触发

**Comment by yukaihua1997** [comment]
点击事件通过事件代理已解决，但是第一次加载时，快速滚过第一项的问题依然存在！

**Comment by chenxuan0000** [comment]
@yukaihua1997 第一次滚动设置默认autoPlay为true,立马滚动，如果想实现你要效果，默认改成false，后面动态改成true。
