### ISSUE TITLE
将配置中的step改变，能明显感觉到渲染页面时明显抖动，请问一下该如何解决？

### ISSUE THREAD

**Issue by ytxs** [chenxuan0000/vue-seamless-scroll#98]
classOption: {
        step: 0.2
      }
配置中只设置了step的值， 值越小元素渲染时抖动越明显，请问一下各位大佬这该如何解决？

**Comment by chenxuan0000** [comment]
@ytxs 
![image](https://user-images.githubusercontent.com/23030433/71353232-614c8580-25b3-11ea-8b99-d05e6f75b1af.png)
